### ISSUE TITLE
Kscript is broken on ArchLinux

### ISSUE THREAD

**Issue by CLOVIS-AI** [kscripting/kscript#371]
Installed from the AUR.

Error message:
```shell
$ kscript 'println("Hello world")'
/usr/bin/kscript: line 49: /usr/share/kotlin/bin/kotlin: No such file or directory
```

Correct path to the Kotlin binary:
```shell
$ command -v kotlin
/usr/bin/kotlin
```

I don't really know what information could be of use, don't hesitate to ask for specific information you need.

**Comment by aartiPl** [comment]
Thanks for the report!

Can you please execute in the console:
1) echo $KOTLIN_HOME
2) KOTLIN_RUNNER=1 JAVACMD=echo kotlinc

**Comment by CLOVIS-AI** [comment]
```
$ echo $KOTLIN_HOME

$ KOTLIN_RUNNER=1 JAVACMD=echo kotlinc
-Xmx256M -Xms32M -Dkotlin.home=/usr/share/kotlin -cp /usr/share/kotlin/lib/kotlin-runner.jar org.jetbrains.kotlin.runner.Main
```

**Comment by aartiPl** [comment]
The second line is explaining why you get /usr/share/kotlin path for kotlin. (I am not exactly sure how this line work, but it is used to guess KOTLIN_HOME, if it is not set explicitly).
To make kscript working set your KOTLIN_HOME env variable to /usr , and it should start working. I will keep this issue open to allow other comments and suggestions.

**Comment by CLOVIS-AI** [comment]
It does not seem to fix the problem.

```shell
# .zshrc
export KOTLIN_HOME=/usr
```

```shell
$ echo $KOTLIN_HOME
/usr
$ kscript 'println("Hello world!")'
[kscript] [ERROR] Compilation of scriplet failed:
[kscript] [ERROR] Command     : bash -c /usr/share/kotlin/bin/kotlinc   -d '/home/ivan/.kscript/cache/jar_1075c8348f9943a25627037568233d8f/scriplet.jar' '/home/ivan/.kscript/cache/jar_1075c8348f9943a25627037568233d8f/Scriplet.kts' '/home/ivan/.kscript/cache/jar_1075c8348f9943a25627037568233d8f/Main_Scriplet.kt'
[kscript] [ERROR] Exit Code   : 127   
[kscript] [ERROR] Stdout      : 
[kscript] [ERROR] Stderr      : 
[kscript] [ERROR] bash: line 1: /usr/share/kotlin/bin/kotlinc: No such file or directory
[kscript] [ERROR]
```

I'm not sure why the error message is visually different yet complains about the same thing.

**Comment by aartiPl** [comment]
That's strange. Below you can see the code which is used to resolve kotlin home:

![obraz](https://user-images.githubusercontent.com/1508798/179207819-9a405225-ec96-45d1-a86c-fe02a8947ce4.png)

https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/model/ConfigBuilder.kt

As you can see KOTLIN_HOME env goes first while resolving kotlinc.

**Comment by sfesenko** [comment]
> As you can see KOTLIN_HOME env goes first while resolving kotlinc.
> But here also everything looks okay for me.

It's not ok, since kscript makes wrong assumption about location of kotlin binaries, and doesn't check their actual location.
In archlinux scripts are located in $PATH, not under `$KOTLIN_HOME`.

> pacman -Ql kotlin | grep /bin/
```
kotlin /usr/bin/
kotlin /usr/bin/kotlin
kotlin /usr/bin/kotlinc
kotlin /usr/bin/kotlinc-js
kotlin /usr/bin/kotlinc-jvm
```

**Comment by aartiPl** [comment]
Is KOTLIN_HOME set by some installer e. g. SdkMan, or Kotlin installer? In other distros, KOTLIN_HOME is a separate directory that contains bin and lib. Here is a screenshot from Ubuntu:

![obraz](https://user-images.githubusercontent.com/1508798/187090166-c841d4e9-1d53-4082-abb0-93b044a4fa56.png)

So if it is different in archlinux, I guess there will be needed a patch for KScript to correct that behavior on that specific platform.

**Comment by CLOVIS-AI** [comment]
You can see the list of files here: https://archlinux.org/packages/community/any/kotlin/ (in the section ‘package contents’).

Basically it is just another system package with binaries in `/usr/bin`, JARS in `/usr/share`, etc.

**Comment by sfesenko** [comment]
1. everything fine with sdkman, this issue about Archlinux and [kotlin package](https://archlinux.org/packages/community/any/kotlin/) from official Archlinux repo (as mentioned by @CLOVIS-AI )
2. Assumption, that kotlin binaries are placed in $KOTLIN_HOME/bin is just wrong. 
4. Implementation also doesn't look correct:
    1. `GUESS_KOTLIN_HOME=$(KOTLIN_RUNNER=1 JAVACMD=echo kotlinc)`  ## here it assumes that `kotlinc` is present in $PATH
    2. `KOTLIN_BIN="$KOTLIN_HOME/bin/"` ## then it require, that `kotlin` is present in `$KOTLIN_HOME/bin/` (without any checks)
    4. anyway, KOTLIN_HOME value will be ignored later, so nothing will work:
> $ kscript
/home/sfesenko/.sdkman/candidates/kscript/current/bin/kscript: line 50: /usr/share/kotlin/bin/kotlin: No such file or directory

> $ KOTLIN_HOME=/usr kscript
kscript - Enhanced scripting support for Kotlin on *nix-based systems.
 ...
Copyright : 2022 Holger Brandl
License   : MIT
Version   : v4.1.1
Website   : https://github.com/holgerbrandl/kscript


> $ **KOTLIN_HOME=/usr** kscript println
[kscript] [ERROR] Compilation of scriplet failed:
[kscript] [ERROR] Command     : 'bash -c **/usr/share/kotlin/bin/kotlinc**   -d '/home/sfesenko/.cache/kscript/jar_b58e7483b3914effc9ffa9c6ce4fb765/scriplet.jar' '/home/sfesenko/.cache/kscript/jar_b58e7483b3914effc9ffa9c6ce4fb765/Scriplet.kts' '/home/sfesenko/.cache/kscript/jar_b58e7483b3914effc9ffa9c6ce4fb765/Main_Scriplet.kt''
[kscript] [ERROR] Exit Code   : 127   
[kscript] [ERROR] Stdout      : ''
[kscript] [ERROR] Stderr      : 'bash: line 1: **/usr/share/kotlin/bin/kotlinc**: No such file or directory[nl]'
[kscript] [ERROR] 

Since it already assumes, that  `kotlin`/`kotlinc` are available in $PATH, all logic around `$KOTLIN_HOME/bin/` may be removed and issue should be fixed.
Also I believe, that bash is not required to run `kotlin`/`kotlinc` (they don't have to be bash scripts)
As alternative option - kscript may embed `kotlin`/`kotlinc` logic, and just run `java` command, so it won't depend on bash / cmd/ kotlin  / kotlinc / etc and won't run jvm multiple times (kscript will require either $KOTLIN_HOME or `kotlin` in $PATH to calculate $KOTLIN_HOME),

**Comment by sfesenko** [comment]
4.0.0 is last version that works
Added dockerfile as test

this succeed
> docker build -t kts --build-arg VERSION=4.0.0 .

but this failed
> docker build -t kts --build-arg VERSION=4.1.0 .

[Dockerfile](https://github.com/kscripting/kscript/files/9459895/Dockerfile.txt)

**Comment by aartiPl** [comment]
Thanks a lot for checking! I plan to do one more big rework in kscript so that refactoring might resolve this issue. However, I will keep this issue open as it is an important use case.

**Comment by DareFox** [comment]
Tried to fix problem with ignored **KOTLIN_HOME**=/usr variable value. Turns out `kotlinc` automatically overwrites it with 
`/usr/share/kotlin` value

![image](https://user-images.githubusercontent.com/47672780/195229145-d9bdbd58-7bdc-4b6f-b377-a1543fab3564.png)

The only way I found to bypass this behavior is to change the name of KOTLIN_HOME in bash launch script like this: 

`src/kscript`
```diff
## run it using command substitution to have just the user process once kscript is done
- COMMAND=$("${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "$OSTYPE" "$@")
+ COMMAND=$(export KOTLIN_HOME_BYPASS=$KOTLIN_HOME; "${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "$OSTYPE" "$@")

```

And read it value from ConfigBuilder
`src/main/kotlin/../model/ConfigBuilder.kt`
```diff
private fun resolveKotlinHome(osType: OsType): OsPath = path(
+   System.getenv("KOTLIN_HOME_BYPASS") ?:
    System.getenv("KOTLIN_HOME") ?:
    ShellUtils.guessKotlinHome(osType) ?:
    throw IllegalStateException("KOTLIN_HOME is not set and could not be inferred from context.")
)
```

This solved the problem with kscript finding `kotlinc` binary, but now I get a "NoClassDefFoundError" error because the stdlib JAR files are exist separately in `/usr/share/kotlin/libs`

```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/script/templates/standard/ScriptTemplateWithArgs
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at Main_Scriplet$Companion.main(Main_Scriplet.kt:5)
        at Main_Scriplet.main(Main_Scriplet.kt)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:70)
        at org.jetbrains.kotlin.runner.Main.run(Main.kt:188)
        at org.jetbrains.kotlin.runner.Main.main(Main.kt:198)
Caused by: java.lang.ClassNotFoundException: kotlin.script.templates.standard.ScriptTemplateWithArgs
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

```

**Comment by DareFox** [comment]
Found fix, just create symlink to `kotlinc` in `/usr/share/kotlin/bin`

```shell
 sudo mkdir /usr/share/kotlin/bin
 sudo ln -s /usr/bin/kotlin /usr/share/kotlin/bin/kotlin   
 sudo ln -s /usr/bin/kotlinc /usr/share/kotlin/bin/kotlinc   
```
![image](https://user-images.githubusercontent.com/47672780/195329550-cfa0bacf-c2ba-4618-b196-de3f90d1b932.png)

Maybe add this commands to `PKGBUILD` on Aur?

**Comment by aartiPl** [comment]
> Found fix, just create symlink to `kotlinc` in `/usr/share/kotlin/bin`
> 
> ```shell
>  sudo mkdir /usr/share/kotlin/bin
>  sudo ln -s /usr/bin/kotlin /usr/share/kotlin/bin/kotlin   
>  sudo ln -s /usr/bin/kotlinc /usr/share/kotlin/bin/kotlinc   
> ```

@DareFox - this is a nice workaround - thanks for bringing it here.

Another workaround would be to install Kotlin using sdkman (alongside the system-installed one), as in kscript installation guide. That should also fix the problem, although I haven't tested it on ArchLinux.

**Comment by aartiPl** [comment]
@DareFox - I think those symbolic links should be added in the Kotlin package rather than in the KScript. This way, the behavior on the ArchLinux will be consistent with the Kotlin installation directory structure on other systems. And in fact, I think this is the best of all solutions discussed above.

Can you try to push the change to the maintainer of the Kotlin package on ArchLinux?

**Comment by aartiPl** [comment]
I have added information about the problem in the README file with a link to this ticket.

**Comment by aartiPl** [comment]
@ here - I need some help with releasing to ArchLinux. Please have a look at:
https://github.com/kscripting/kscript/issues/376#issuecomment-1373627510

If you know how to solve that problem, please comment: 
https://github.com/kscripting/kscript/issues/376
